import Semester from '../enums/Semester'

export default (sequelize, DataTypes) =>
  sequelize.define('SubjectChoicesVersion', {
    date: { type: DataTypes.STRING, allowNull: false },
    semester: { type: DataTypes.ENUM, values: Semester, allowNull: false },
    isActive: { type: DataTypes.BOOLEAN, allowNull: false, field: 'is_active' }
  }, {
    comment: 'Store the versions of final student choices generated by the algorithm',
    timestamps: false,
    freezeTableName: true
  })
